[package]
name = "demo"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"] }
toml = "0.8"
fontdb = "0.16"
log = "0.4"
rust-i18n = { version = "4.2", features = ["log-miss-tr"] }
ply-engine = { version = "1.1", default-features = false, features = ["a11y", "built-in-shaders", "text-styling"] }

[build-dependencies]
ply-engine = {
  version = "1.1",
  default-features = false,
  features = ["shader-build"]
}
# This line needs to come before anything else in Cargo.toml
#
